on:
  workflow_call:
    inputs: 
      repository: 
        required: true
        type: string
      agent: 
        required: true
        type: string
      build-path: 
        required: true
        type: string
jobs:        
  Build_JDK11:
    if: ${{ inputs.agent == 'jdk11' }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup-Java
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'
          overwrite-settings: false
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
      - run: |
          echo "mvn -f ${{ inputs.path }}/pom.xml clean install package"
      
  Build_JDK8:
    if: ${{ inputs.agent == 'jdk8' }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup-Java
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '8'
          overwrite-settings: false
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
      - run: |
          echo "mvn -f ${{ inputs.path }}/pom.xml clean install package"       
