name: CICD JDK11 WORKFLOW
on: 
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      path:
        required: true
        type: string        
jobs: 
  Build:  
    runs-on: ubuntu-latest
    steps:
      - name: Setup-Java
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'
      #    overwrite-settings: false
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
      - run: |
          mvn -f ${{ inputs.path }}/pom.xml clean install package




