name: CICD MAIN WORKFLOW
on: 
  workflow_call:
    inputs:
      application:
        required: true
        type: string
      technology:
        required: true
        type: string  
jobs: 
  welcome:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Welcome to the CICD process for ${{ inputs.application }} application"
    
  validate:     
    uses: ./.github/workflows/validation.yml
    needs: welcome
    with: 
      application: ${{ inputs.application }}
      
  sonar-scan:     
    uses: ./.github/workflows/sonar-scan.yml
    needs: [welcome,validate]
    with: 
      application: ${{ inputs.application }}
