name: SONNAR SCAN
on:
  workflow_call:
    inputs:
      application:
        required: true
        type: string  
jobs:
 sonar-scan:
  runs-on: self-hosted
  steps:
    - name: Official SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v2.0.2
      with:
        projectBaseDir: app/src
        args: >
          -Dsonar.projectKey=${{ inputs.application }}
          -Dsonar.python.coverage.reportPaths=coverage.xml
          -Dsonar.tests=tests/
          -Dsonar.verbose=true
            
