name: VALIDATION STEP
on:
  workflow_dispatch:
    inputs:
      application:
        required: true
        type: string  
  workflow_call:
    inputs:
      application:
        required: true
        type: string
jobs:
 validation:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v4
    with:
      repository: 'lbasg/${{ inputs.application }}'
  - name: load Iberdrolafile
    run: cat ./Iberdrolafile
