name: VALIDATION STEP
on:
  workflow_dispatch:
    inputs:
      application:
        required: true
        type: string  
  workflow_call:
    inputs:
      application:
        required: true
        type: string
jobs:
 validation:
  runs-on: ubuntu-latest
  steps:
  - run: echo ${{ inputs.application }}
