on:
  workflow_dispatch:
  workflow_call:
    inputs:
      application:
        required: true
        type: string
jobs:
 reusable_workflow_job:
  runs-on: ubuntu-latest
  steps:
  - run: echo ${{ inputs.application }}
